# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_bug_1138550_unified_clones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='forest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repositories', to='life.Forest'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='locale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='life.Locale'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='l10n',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='life.Forest'),
        ),
    ]
