# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-16 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0003_bug_1353850_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.TextField(help_text='name of the branch'),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='user',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='push',
            name='push_date',
            field=models.DateTimeField(db_index=True, verbose_name='date of push'),
        ),
    ]
