# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-19 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mbdb', '0001_squashed_0003_bug_1353850_on_delete'),
        ('life', '0001_squashed_0004_auto_20191116_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srctime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('missing', models.IntegerField(default=0)),
                ('missingInFiles', models.IntegerField(default=0)),
                ('obsolete', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('changed', models.IntegerField(default=0)),
                ('unchanged', models.IntegerField(default=0)),
                ('keys', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('report', models.IntegerField(default=0)),
                ('warnings', models.IntegerField(default=0)),
                ('completion', models.SmallIntegerField(default=0)),
                ('build', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mbdb.Build')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life.Locale')),
                ('revisions', models.ManyToManyField(to='life.Changeset')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life.Tree')),
            ],
        ),
        migrations.AddField(
            model_name='active',
            name='run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='l10nstats.Run'),
        ),
    ]
