# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 16:00
from __future__ import unicode_literals
from __future__ import absolute_import

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l10nstats', '0002_bug_1365748_drop_file_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressposition',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='progressposition',
            name='tree',
        ),
        migrations.DeleteModel(
            name='ProgressPosition',
        ),
    ]
