# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-19 09:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import privacy.models


class Migration(migrations.Migration):

    replaces = [('privacy', '0001_initial'), ('privacy', '0002_auto_20191116_1511')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            bases=(models.Model, privacy.models.CTMixin),
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='use html markup')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('activate_policy', 'Can activate a policy'),),
            },
            bases=(models.Model, privacy.models.CTMixin),
        ),
        migrations.AddField(
            model_name='comment',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='privacy.Policy'),
        ),
        migrations.AddField(
            model_name='comment',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
