# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-16 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='text',
            field=models.TextField(help_text='use html markup'),
        ),
    ]
