# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 10:00
from __future__ import unicode_literals

from django.db import migrations


# Snapshot of lib.auth.backends.MAPPING.values()
GROUPS = ("Localizers",)


def ensure_ldap_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for django_group in GROUPS:
        Group.objects.get_or_create(name=django_group)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length')
    ]

    operations = [
        migrations.RunPython(
            ensure_ldap_groups,
            migrations.RunPython.noop
        ),
    ]
