# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-19 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mbdb.fields


class Migration(migrations.Migration):

    replaces = [('mbdb', '0001_initial'), ('mbdb', '0002_bug_1333398_property_length'), ('mbdb', '0003_bug_1353850_on_delete')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildnumber', models.IntegerField(db_index=True, null=True)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('result', models.SmallIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('bigState', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitTime', models.DateTimeField()),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbdb.Builder')),
                ('builds', models.ManyToManyField(related_name='requests', to='mbdb.Build')),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('revision', models.CharField(blank=True, max_length=50, null=True)),
                ('who', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('when', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('filename', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('isFinished', models.BooleanField(default=False)),
                ('html', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumberedChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbered_changes', to='mbdb.Change')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('source', models.CharField(db_index=True, max_length=20)),
                ('value', mbdb.fields.PickledObjectField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('revision', models.CharField(blank=True, max_length=50, null=True)),
                ('changes', models.ManyToManyField(related_name='stamps', through='mbdb.NumberedChange', to='mbdb.Change')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', mbdb.fields.ListField(blank=True, null=True)),
                ('text2', mbdb.fields.ListField(blank=True, null=True)),
                ('result', models.SmallIntegerField(blank=True, null=True)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='mbdb.Build')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='mbdb.Step')),
            ],
        ),
        migrations.AddField(
            model_name='numberedchange',
            name='sourcestamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbered_changes', to='mbdb.SourceStamp'),
        ),
        migrations.AddField(
            model_name='log',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mbdb.Step'),
        ),
        migrations.AddField(
            model_name='change',
            name='files',
            field=models.ManyToManyField(to='mbdb.File'),
        ),
        migrations.AddField(
            model_name='change',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbdb.Master'),
        ),
        migrations.AddField(
            model_name='change',
            name='tags',
            field=models.ManyToManyField(to='mbdb.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='change',
            unique_together=set([('number', 'master')]),
        ),
        migrations.AddField(
            model_name='buildrequest',
            name='sourcestamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='mbdb.SourceStamp'),
        ),
        migrations.AddField(
            model_name='builder',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builders', to='mbdb.Master'),
        ),
        migrations.AddField(
            model_name='build',
            name='builder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='mbdb.Builder'),
        ),
        migrations.AddField(
            model_name='build',
            name='properties',
            field=models.ManyToManyField(related_name='builds', to='mbdb.Property'),
        ),
        migrations.AddField(
            model_name='build',
            name='slave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mbdb.Slave'),
        ),
        migrations.AddField(
            model_name='build',
            name='sourcestamp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='mbdb.SourceStamp'),
        ),
    ]
