# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mbdb', '0002_bug_1333398_property_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='slave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mbdb.Slave'),
        ),
        migrations.AlterField(
            model_name='build',
            name='sourcestamp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='mbdb.SourceStamp'),
        ),
    ]
