# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-19 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('tinder', '0001_initial'), ('tinder', '0002_drop_mastermap')]

    initial = True

    dependencies = [
        ('mbdb', '0001_initial'),
    ]

    operations = [
    ]
