# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-15 12:03
from __future__ import unicode_literals

from collections import defaultdict

from django.db import migrations


def remove_stale_contenttypes(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    stale_ids = []
    stale_models = defaultdict(list)
    for ct in ContentType.objects.all():
        try:
            apps.get_model(ct.app_label, ct.model)
        except LookupError:
            stale_ids.append(ct.id)
            stale_models[ct.app_label].append(ct.model)
    if not stale_ids:
        return
    print('Removing stale ContentTypes for:')
    for app, models in sorted(stale_models.items()):
        print(app, ': ', ', '.join(sorted(models)))
    ContentType.objects.filter(id__in=stale_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0001_initial'),
        ('l10nstats', '0003_drop_progress_position'),
        ('life', '0003_bug_1353850_on_delete'),
        ('mbdb', '0003_bug_1353850_on_delete'),
        ('privacy', '0001_initial'),
        ('shipping', '0003_auto_20160729_1128'),
        ('tinder', '0002_drop_mastermap')
    ]

    operations = [
        migrations.RunPython(
            remove_stale_contenttypes,
            migrations.RunPython.noop
        ),
    ]
