# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-16 15:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_auto_20160729_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='flag',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'accepted'), (2, 'rejected'), (3, 'canceled'), (4, 'obsoleted')]),
        ),
        migrations.AlterField(
            model_name='action',
            name='when',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='signoff action timestamp'),
        ),
        migrations.AlterField(
            model_name='signoff',
            name='when',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='signoff timestamp'),
        ),
    ]
